### ISSUE TITLE
Can this work on URLs?

### ISSUE THREAD

**Issue by mledwards** [texthtml/php-lock#5]
It would be great if I could do this on URLs for editing purposes. Thanks.

**Comment by mathroc** [comment]
what to you mean ? can you give me a code example of what you would like to write ?

**Comment by mledwards** [comment]
Pass in a URL instead of a file path :)

**Comment by mathroc** [comment]
well `FileLock` uses [flock](http://php.net/flock) which can only lock files. but, you can do something like that :

```php
use TH\Lock\FileFactory;

$factory = new FileFactory(sys_get_temp_dir());
$lock = $factory->create('https://some.url/'');
```

would that works for you ?

**Comment by mledwards** [comment]
I'll give that a try, thanks!

**Comment by mathroc** [comment]
closing, please reopen if needed
